"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
import os
import sys
import environ
import oracledb
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Oracle Thick 모드 활성화 (Oracle XE 21c 설치 경로 명시)
# Django autoreloader 사용 시 부모(watcher) 프로세스에서는 초기화 건너뜀.
# 부모가 Oracle 자원을 선점하면 자식 프로세스의 연결이 ORA-01017로 실패하기 때문.
# RUN_MAIN=true → autoreloader 자식 프로세스 (실제 서버)
# RUN_MAIN 없음 → --noreload 단일 프로세스 또는 다른 관리 명령어
_is_runserver_parent = (
    'runserver' in sys.argv
    and '--noreload' not in sys.argv
    and os.environ.get('RUN_MAIN') != 'true'
)
if not _is_runserver_parent:
    _oracle_lib = os.environ.get('ORACLE_LIB_DIR', r"C:\app\WEBD\product\21c\dbhomeXE\bin")
    # 아래 라이브러리 초기화 코드를 주석 처리하여 Thin 모드로 작동시킵니다.
    # oracledb.init_oracle_client(lib_dir=_oracle_lib)

# environ 객체 초기화 및 .env 파일 로드
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=True)

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # DRF
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    # CORS
    'corsheaders',

    # 서비스 앱
    'Users.apps.UsersConfig',
    'Products',
    'Orders',
    'payments',
    'coupons',
]

AUTH_USER_MODEL = 'Users.User'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database — 환경 변수(.env) 기반 Oracle 연동
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': env('DB_NAME', default='XE'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='1521'),

        'TEST': {
            'USER': 'C##TEST_ELITE_NEW',
            'TBSPACE': 'TEST_C##ELITE_NEW_TB',
            'DEPENDENCIES': [],
        }
    }
}



# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True


# Static files

STATIC_URL = 'static/'


# test 실행 시 SQLite 인메모리 DB로 스위칭
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

load_dotenv()


# JWT 토큰 유효기간
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': env('JWT_SECRET_KEY', default=SECRET_KEY),
    'ALGORITHM': 'HS256',
}


# DRF 기본 인증/권한 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'Users.users.CustomJWTAuthentication',  # Django JWT + Spring Boot JWT 모두 처리
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'debug.log'),
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django.request': {'handlers': ['file'], 'level': 'ERROR', 'propagate': False},
        'Users': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': True},
    },
}

# hCaptcha 시크릿 키
HCAPTCHA_SECRET_KEY = env('HCAPTCHA_SECRET_KEY', default='')

# 포트원 결제
PORTONE_STORE_ID = env('PORTONE_STORE_ID', default='')
PORTONE_CHANNEL_KEY = env('PORTONE_CHANNEL_KEY', default='')
PORTONE_API_SECRET = env('PORTONE_API_SECRET', default='')

# 이메일 백엔드 설정 (개발: 콘솔 출력 / 운영: SMTP 발송)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@jipdaum.local'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.naver.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER', default='')



