"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

이 프로젝트는 회원/상품/쿠폰/결제/챗봇 API를 전부 Spring Boot(jipdaum-spring)로 이관했고,
Django는 관리자 화면(/admin/) 전용으로 스코프를 좁혔다. DRF/JWT/CORS는 그 API들을 위한
설정이었기 때문에 여기서도 함께 제거했다 — MySQL 스키마 소유권(마이그레이션)만 계속 Django가 갖는다.
"""
import os
import sys
import environ
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# environ 객체 초기화 및 .env 파일 로드
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=True)

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 서비스 앱 — API는 다 걷어냈지만 모델/마이그레이션은 admin과 스키마 소유권을 위해 유지
    'Users.apps.UsersConfig',
    'Products',
    'Orders',
    'payments',
    'coupons',
    'Inquiries',
]

AUTH_USER_MODEL = 'Users.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database — 환경 변수(.env) 기반 MySQL 연동
# DEBUG=True(로컬)면 docker-compose.yml의 MySQL 컨테이너 기본값으로 접속,
# DEBUG=False(운영)면 값 누락 시 기본값 없이 즉시 에러를 내서 배포 설정 누락을 방지한다.
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('DB_NAME', default='jibdaum'),
            'USER': env('DB_USER', default='root'),
            'PASSWORD': env('DB_PASSWORD', default='rootpassword'),
            'HOST': env('DB_HOST', default='127.0.0.1'),
            'PORT': env('DB_PORT', default='3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT', default='3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }



# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True


# Static files — admin(/admin/) CSS/JS를 gunicorn 단독 배포에서도 서빙하기 위해 whitenoise 사용.
# collectstatic 산출물은 컨테이너 시작 시 entrypoint.sh가 만든다(STATIC_ROOT).

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# test 실행 시 SQLite 인메모리 DB로 스위칭
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

load_dotenv()


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'debug.log'),
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django.request': {'handlers': ['file'], 'level': 'ERROR', 'propagate': False},
        'Users': {'handlers': ['console', 'file'], 'level': 'DEBUG', 'propagate': True},
    },
}

