# Generated by Django 6.0.5 on 2026-06-05 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니 목록',
                'db_table': 'JIPDAUM_CART',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='ORDERED', max_length=50)),
                ('shipping_addr', models.CharField(max_length=500)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '주문 마스터',
                'verbose_name_plural': '주문 마스터 목록',
                'db_table': 'JIPDAUM_ORDER',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ordered_price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '주문 상세 내역',
                'verbose_name_plural': '주문 상세 내역 목록',
                'db_table': 'JIPDAUM_ORDER_ITEM',
            },
        ),
    ]
