# Generated by Django 6.0.5 on 2026-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '결제대기'), ('ORDERED', '주문완료(결제완료)'), ('SHIPPED', '배송중'), ('DELIVERED', '배송완료'), ('CANCELLED', '주문취소')], default='ORDERED', max_length=50),
        ),
    ]
