# Generated by Django 6.0.5 on 2026-07-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_order_carrier_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='택배사'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='운송장 번호'),
        ),
    ]
