# Generated by Django 6.0.5 on 2026-06-05 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='Products.category')),
            ],
            options={
                'verbose_name': '상품 카테고리',
                'verbose_name_plural': '상품 카테고리 목록',
                'db_table': 'JIPDAUM_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.category')),
            ],
            options={
                'verbose_name': '상품 마스터',
                'verbose_name_plural': '상품 마스터 목록',
                'db_table': 'JIPDAUM_PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=100)),
                ('option_value', models.CharField(max_length=100)),
                ('extra_price', models.IntegerField(default=0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Products.product')),
            ],
            options={
                'verbose_name': '상품 옵션',
                'verbose_name_plural': '상품 옵션 목록',
                'db_table': 'JIPDAUM_PRODUCT_OPTION',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('review_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Products.product')),
            ],
            options={
                'verbose_name': '상품 리뷰',
                'verbose_name_plural': '상품 리뷰 목록',
                'db_table': 'JIPDAUM_REVIEW',
            },
        ),
    ]
