# Generated by Django 6.0.5 on 2026-08-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
