# Generated by Django 6.0.5 on 2026-08-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('main', '메인'), ('korean_hall', '한국관')], default='main', max_length=20),
        ),
    ]
