-- ====================================================================
-- [Jipdaum] 집다움 오라클 DB 구축 최종 통합 DDL 스크립트
-- 작성일자: 2026. 06. 02
-- 데이터베이스: Oracle 12c / 19c / 21c 이상 호환
-- 설명: Django ORM 고도화 스펙 (AbstractUser, ManyToMany through, 
--       결제 및 테이블스냅샷)이 완벽히 반영된 최종 물리 스키마
-- ====================================================================

------------------------------------------------------------------------
-- 0. 기존 테이블 및 시퀀스 DROP (초기화용)
------------------------------------------------------------------------
/*
DROP TABLE JIPDAUM_POST_SCRAP CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_POST_LIKE CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_POST_IMAGE CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_POST_TAGGED_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_POST CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_ORDER_ITEM CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_ORDER CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_REVIEW CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_CART CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_PRODUCT_OPTION CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_USER CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_NOTICE CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_BANNER CASCADE CONSTRAINTS;
DROP TABLE JIPDAUM_STYLE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_JIPDAUM_USER;
DROP SEQUENCE SEQ_JIPDAUM_STYLE;
DROP SEQUENCE SEQ_JIPDAUM_BANNER;
DROP SEQUENCE SEQ_JIPDAUM_NOTICE;
DROP SEQUENCE SEQ_JIPDAUM_CATEGORY;
DROP SEQUENCE SEQ_JIPDAUM_PRODUCT;
DROP SEQUENCE SEQ_JIPDAUM_PRODUCT_OPTION;
DROP SEQUENCE SEQ_JIPDAUM_POST;
DROP SEQUENCE SEQ_JIPDAUM_POST_TAGGED_PRODUCT;
DROP SEQUENCE SEQ_JIPDAUM_POST_IMAGE;
DROP SEQUENCE SEQ_JIPDAUM_CART;
DROP SEQUENCE SEQ_JIPDAUM_REVIEW;
DROP SEQUENCE SEQ_JIPDAUM_ORDER;
DROP SEQUENCE SEQ_JIPDAUM_ORDER_ITEM;
DROP SEQUENCE SEQ_JIPDAUM_PAYMENT;
*/

------------------------------------------------------------------------
-- 1. 시퀀스(Sequence) 생성
------------------------------------------------------------------------
CREATE SEQUENCE SEQ_JIPDAUM_USER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_STYLE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_BANNER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_NOTICE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_PRODUCT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_PRODUCT_OPTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_POST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_POST_TAGGED_PRODUCT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_POST_IMAGE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_CART START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_ORDER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_ORDER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_JIPDAUM_PAYMENT START WITH 1 INCREMENT BY 1 NOCACHE;


------------------------------------------------------------------------
-- 2. 테이블 생성 (참조 무결성 관계 고려 순서 배치)
------------------------------------------------------------------------

-- [1] 사용자 마스터 테이블 (Django AbstractUser 인증 필드 확장 반영)
CREATE TABLE JIPDAUM_USER (
    id           NUMBER(11) NOT NULL,
    username     VARCHAR2(150) NOT NULL,
    password     VARCHAR2(255) NOT NULL,
    nickname     VARCHAR2(100) NOT NULL,
    email        VARCHAR2(100) NOT NULL,
    is_staff     NUMBER(1) DEFAULT 0 NOT NULL,      -- 스태프 권한 (0:False, 1:True)
    is_active    NUMBER(1) DEFAULT 1 NOT NULL,      -- 계정 활성 여부 (0:False, 1:True)
    is_superuser NUMBER(1) DEFAULT 0 NOT NULL,      -- 최고 관리자 여부 (0:False, 1:True)
    first_name   VARCHAR2(150) NULL,
    last_name    VARCHAR2(150) NULL,
    last_login   TIMESTAMP NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_USER PRIMARY KEY (id),
    CONSTRAINT UK_JIPDAUM_USER_USERNAME UNIQUE (username),
    CONSTRAINT UK_JIPDAUM_USER_EMAIL UNIQUE (email),
    CONSTRAINT CK_JIPDAUM_USER_IS_STAFF CHECK (is_staff IN (0, 1)),
    CONSTRAINT CK_JIPDAUM_USER_IS_ACTIVE CHECK (is_active IN (0, 1)),
    CONSTRAINT CK_JIPDAUM_USER_IS_SUPER CHECK (is_superuser IN (0, 1))
);

-- [2] 인테리어 스타일 태그 테이블
CREATE TABLE JIPDAUM_STYLE (
    id          NUMBER(11) NOT NULL,
    name        VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_JIPDAUM_STYLE PRIMARY KEY (id)
);

-- [3] 홈 메인 배너 관리 테이블
CREATE TABLE JIPDAUM_BANNER (
    id          NUMBER(11) NOT NULL,
    title       VARCHAR2(200) NOT NULL,
    subtitle    VARCHAR2(300) NULL,
    image_url   VARCHAR2(500) NOT NULL,
    link_url    VARCHAR2(500) NULL,
    is_active   NUMBER(1) DEFAULT 1 NOT NULL,      -- 노출 여부 (0:False, 1:True)
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_BANNER PRIMARY KEY (id),
    CONSTRAINT CK_JIPDAUM_BANNER_ACTIVE CHECK (is_active IN (0, 1))
);

-- [4] 서비스 공지사항 테이블
CREATE TABLE JIPDAUM_NOTICE (
    id          NUMBER(11) NOT NULL,
    title       VARCHAR2(200) NOT NULL,
    content     CLOB NOT NULL,
    is_active   NUMBER(1) DEFAULT 1 NOT NULL,      -- 활성화 여부 (0:False, 1:True)
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_NOTICE PRIMARY KEY (id),
    CONSTRAINT CK_JIPDAUM_NOTICE_ACTIVE CHECK (is_active IN (0, 1))
);

-- [5] 상품 카테고리 테이블 (셀프 참조 계층형 구조)
CREATE TABLE JIPDAUM_CATEGORY (
    id          NUMBER(11) NOT NULL,
    name        VARCHAR2(100) NOT NULL,
    parent_id   NUMBER(11) NULL,
    CONSTRAINT PK_JIPDAUM_CATEGORY PRIMARY KEY (id),
    CONSTRAINT FK_JIPDAUM_CAT_PARENT FOREIGN KEY (parent_id) 
        REFERENCES JIPDAUM_CATEGORY(id) ON DELETE SET NULL
);

-- [6] 상품 마스터 테이블
CREATE TABLE JIPDAUM_PRODUCT (
    id            NUMBER(11) NOT NULL,
    category_id   NUMBER(11) NOT NULL,
    name          VARCHAR2(200) NOT NULL,
    brand         VARCHAR2(100) NOT NULL,
    base_price    NUMBER(11) DEFAULT 0 NOT NULL,
    description   CLOB NOT NULL,
    thumbnail_url VARCHAR2(500) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_PRODUCT PRIMARY KEY (id),
    CONSTRAINT FK_JIPDAUM_PROD_CAT FOREIGN KEY (category_id) 
        REFERENCES JIPDAUM_CATEGORY(id) ON DELETE CASCADE,
    CONSTRAINT CK_JIPDAUM_PROD_PRICE CHECK (base_price >= 0)
);

-- [7] 상품 옵션 상세 정보 테이블
CREATE TABLE JIPDAUM_PRODUCT_OPTION (
    id            NUMBER(11) NOT NULL,
    product_id    NUMBER(11) NOT NULL,
    option_name   VARCHAR2(100) NOT NULL,
    option_value  VARCHAR2(100) NOT NULL,
    extra_price   NUMBER(11) DEFAULT 0 NOT NULL,   -- 차감 금액 가능성 대비 체크조건 배제
    stock_count   NUMBER(11) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JIPDAUM_PRODUCT_OPTION PRIMARY KEY (id),
    CONSTRAINT FK_JIPDAUM_OPT_PROD FOREIGN KEY (product_id) 
        REFERENCES JIPDAUM_PRODUCT(id) ON DELETE CASCADE,
    CONSTRAINT CK_JIPDAUM_OPT_STOCK CHECK (stock_count >= 0)
);

-- [8] 독립 장바구니 테이블 (아이템 단일 최적화 구조)
CREATE TABLE JIPDAUM_CART (
    id          NUMBER(11) NOT NULL,
    user_id     NUMBER(11) NOT NULL,
    product_id  NUMBER(11) NOT NULL,
    option_id   NUMBER(11) NULL,                   -- 옵션 없는 상품 허용
    quantity    NUMBER(11) DEFAULT 1 NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_CART PRIMARY KEY (id),
    CONSTRAINT FK_CART_USER FOREIGN KEY (user_id) 
        REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (product_id) 
        REFERENCES JIPDAUM_PRODUCT(id) ON DELETE CASCADE,
    CONSTRAINT FK_CART_OPTION FOREIGN KEY (option_id) 
        REFERENCES JIPDAUM_PRODUCT_OPTION(id) ON DELETE SET NULL,
    CONSTRAINT UK_USER_PROD_OPT UNIQUE (user_id, product_id, option_id),
    CONSTRAINT CK_JIPDAUM_CART_QTY CHECK (quantity > 0)
);

-- [9] 상품 구매 리뷰 테이블
CREATE TABLE JIPDAUM_REVIEW (
    id               NUMBER(11) NOT NULL,
    product_id       NUMBER(11) NOT NULL,
    user_id          NUMBER(11) NOT NULL,
    rating           NUMBER(2) DEFAULT 5 NOT NULL,
    comment          CLOB NOT NULL,
    review_image_url VARCHAR2(500) NULL,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_REVIEW PRIMARY KEY (id),
    CONSTRAINT FK_REVIEW_PRODUCT FOREIGN KEY (product_id) 
        REFERENCES JIPDAUM_PRODUCT(id) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEW_USER FOREIGN KEY (user_id) 
        REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT CK_JIPDAUM_REV_RATING CHECK (rating BETWEEN 1 AND 5)
);

-- [10] 결제 완료된 영구 주문 마스터 테이블
CREATE TABLE JIPDAUM_ORDER (
    id            NUMBER(11) NOT NULL,
    user_id       NUMBER(11) NOT NULL,
    total_amount  NUMBER(11) NOT NULL,
    status        VARCHAR2(50) DEFAULT 'ORDERED' NOT NULL,
    shipping_addr VARCHAR2(500) NOT NULL,
    order_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_ORDER PRIMARY KEY (id),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (user_id) 
        REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT CK_JIPDAUM_ORD_AMT CHECK (total_amount >= 0)
);

-- [11] 주문 상세 내역 및 금액 스냅샷 테이블
CREATE TABLE JIPDAUM_ORDER_ITEM (
    id            NUMBER(11) NOT NULL,
    order_id      NUMBER(11) NOT NULL,
    product_id    NUMBER(11) NOT NULL,
    option_id     NUMBER(11) NULL,
    quantity      NUMBER(11) DEFAULT 1 NOT NULL,
    ordered_price NUMBER(11) NOT NULL,             -- 주문 당시 단가 스냅샷
    CONSTRAINT PK_JIPDAUM_ORDER_ITEM PRIMARY KEY (id),
    CONSTRAINT FK_ITEM_ORDER FOREIGN KEY (order_id) 
        REFERENCES JIPDAUM_ORDER(id) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_PRODUCT FOREIGN KEY (product_id) 
        REFERENCES JIPDAUM_PRODUCT(id) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_OPTION FOREIGN KEY (option_id) 
        REFERENCES JIPDAUM_PRODUCT_OPTION(id) ON DELETE SET NULL,
    CONSTRAINT CK_JIPDAUM_ITEM_QTY CHECK (quantity > 0),
    CONSTRAINT CK_JIPDAUM_ITEM_PRICE CHECK (ordered_price >= 0)
);

-- [12] 주문 결제 정보 관리 테이블 (Order와 1:1 관계 구현)
CREATE TABLE JIPDAUM_PAYMENT (
    id             NUMBER(11) NOT NULL,
    order_id       NUMBER(11) NOT NULL,
    user_id        NUMBER(11) NOT NULL,
    method         VARCHAR2(50) NOT NULL,
    status         VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    amount         NUMBER(11) NOT NULL,
    transaction_id VARCHAR2(200) NULL,
    paid_at        TIMESTAMP NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_PAYMENT PRIMARY KEY (id),
    CONSTRAINT UK_JIPDAUM_PAYMENT_ORDER UNIQUE (order_id),
    CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (order_id) 
        REFERENCES JIPDAUM_ORDER(id) ON DELETE CASCADE,
    CONSTRAINT FK_PAYMENT_USER FOREIGN KEY (user_id) 
        REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT CK_JIPDAUM_PAY_METHOD CHECK (method IN ('KAKAO', 'TOSS', 'CARD', 'BANK')),
    CONSTRAINT CK_JIPDAUM_PAY_STATUS CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')),
    CONSTRAINT CK_JIPDAUM_PAY_AMOUNT CHECK (amount >= 0)
);

-- [13] 인테리어 피드 집들이 게시글 테이블 (공간타입 및 스타일 외래키 확장)
CREATE TABLE JIPDAUM_POST (
    id          NUMBER(11) NOT NULL,
    user_id     NUMBER(11) NOT NULL,
    title       VARCHAR2(200) NOT NULL,
    content     CLOB NOT NULL,
    image_url   VARCHAR2(500) NOT NULL,            -- 메인 썸네일 이미지 필수 유지
    style_id    NUMBER(11) NULL,                   -- core.Style 참조 연동
    space_type  VARCHAR2(20) NULL,                 -- LIVING_ROOM, BEDROOM 등 공간 필터
    view_count  NUMBER(11) DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_JIPDAUM_POST PRIMARY KEY (id),
    CONSTRAINT FK_JIPDAUM_POST_USER FOREIGN KEY (user_id) 
        REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT FK_JIPDAUM_POST_STYLE FOREIGN KEY (style_id) 
        REFERENCES JIPDAUM_STYLE(id) ON DELETE SET NULL
);

-- [14] 게시글 이미지 위 상품 좌표 태깅 교차 테이블 (ManyToManyField through 완벽 동기화)
CREATE TABLE JIPDAUM_POST_TAGGED_PRODUCT (
    id             NUMBER(11) NOT NULL,
    post_id        NUMBER(11) NOT NULL,
    product_id     NUMBER(11) NOT NULL,
    tag_position_x BINARY_FLOAT DEFAULT 0.0 NOT NULL, -- 이미지 상의 x좌표 백분율
    tag_position_y BINARY_FLOAT DEFAULT 0.0 NOT NULL, -- 이미지 상의 y좌표 백분율
    CONSTRAINT PK_POST_TAGGED_PRODUCT PRIMARY KEY (id),
    CONSTRAINT FK_TAG_POST FOREIGN KEY (post_id) 
        REFERENCES JIPDAUM_POST(id) ON DELETE CASCADE,
    CONSTRAINT FK_TAG_PRODUCT FOREIGN KEY (product_id) 
        REFERENCES JIPDAUM_PRODUCT(id) ON DELETE CASCADE,
    CONSTRAINT UK_POST_PRODUCT UNIQUE (post_id, product_id)
);

-- [15] 피드 서브 공간 다중 사진 관리 테이블
CREATE TABLE JIPDAUM_POST_IMAGE (
    id         NUMBER(11) NOT NULL,
    post_id    NUMBER(11) NOT NULL,
    image_url  VARCHAR2(500) NOT NULL,
    "order"    NUMBER(11) DEFAULT 0 NOT NULL,      -- 순서 정렬 필드 (오라클 예약어 쌍따옴표 이스케이프)
    CONSTRAINT PK_JIPDAUM_POST_IMAGE PRIMARY KEY (id),
    CONSTRAINT FK_IMG_POST FOREIGN KEY (post_id) 
        REFERENCES JIPDAUM_POST(id) ON DELETE CASCADE
);

-- [16] 게시글 좋아요 ManyToMany 전용 브릿지 테이블
CREATE TABLE JIPDAUM_POST_LIKE (
    id       NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  NUMBER(11) NOT NULL,
    user_id  NUMBER(11) NOT NULL,
    CONSTRAINT FK_LIKE_POST FOREIGN KEY (post_id) REFERENCES JIPDAUM_POST(id) ON DELETE CASCADE,
    CONSTRAINT FK_LIKE_USER FOREIGN KEY (user_id) REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT UK_POST_LIKE UNIQUE (post_id, user_id)
);

-- [17] 게시글 스크랩 ManyToMany 전용 브릿지 테이블
CREATE TABLE JIPDAUM_POST_SCRAP (
    id       NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  NUMBER(11) NOT NULL,
    user_id  NUMBER(11) NOT NULL,
    CONSTRAINT FK_SCRAP_POST FOREIGN KEY (post_id) REFERENCES JIPDAUM_POST(id) ON DELETE CASCADE,
    CONSTRAINT FK_SCRAP_USER FOREIGN KEY (user_id) REFERENCES JIPDAUM_USER(id) ON DELETE CASCADE,
    CONSTRAINT UK_POST_SCRAP UNIQUE (post_id, user_id)
);


------------------------------------------------------------------------
-- 3. 테이블 및 데이터 속성 식별 편의를 위한 코멘트(Comment) 정의
------------------------------------------------------------------------
COMMENT ON TABLE JIPDAUM_USER IS 'Django 내장 인증 엔진 확장 사용자 마스터 테이블';
COMMENT ON TABLE JIPDAUM_STYLE IS '인테리어 스타일 태그 마스터 테이블';
COMMENT ON TABLE JIPDAUM_BANNER IS '메인 페이지 배너 관리 테이블';
COMMENT ON TABLE JIPDAUM_NOTICE IS '서비스 공지사항 테이블';
COMMENT ON TABLE JIPDAUM_CATEGORY IS '상품 카테고리 계층형 테이블';
COMMENT ON TABLE JIPDAUM_PRODUCT IS '상품 마스터 테이블';
COMMENT ON TABLE JIPDAUM_PRODUCT_OPTION IS '상품별 옵션 정보 테이블';
COMMENT ON TABLE JIPDAUM_CART IS '사용자별 독단적인 장바구니 아이템 테이블';
COMMENT ON TABLE JIPDAUM_REVIEW IS '상품 구매 리뷰 테이블';
COMMENT ON TABLE JIPDAUM_ORDER IS '결제 완료 주문 기본 마스터 테이블';
COMMENT ON TABLE JIPDAUM_ORDER_ITEM IS '주문 상세 정보 내역 및 가격 스냅샷 테이블';
COMMENT ON TABLE JIPDAUM_PAYMENT IS '주문 결제 정보 마스터 테이블';
COMMENT ON TABLE JIPDAUM_POST IS '인테리어 집들이 게시글 테이블';
COMMENT ON TABLE JIPDAUM_POST_TAGGED_PRODUCT IS '게시글 사진 내 상품 태깅 좌표 교차 테이블';
COMMENT ON TABLE JIPDAUM_POST_IMAGE IS '피드 서브 공간 다중 사진 관리 테이블';

COMMENT ON COLUMN JIPDAUM_USER.is_staff IS '스태프 권한 여부 (0:일반유저, 1:관리자페이지 접근가능)';
COMMENT ON COLUMN JIPDAUM_USER.is_active IS '계정 활성 여부 (0:휴면/탈퇴, 1:활동중)';
COMMENT ON COLUMN JIPDAUM_USER.is_superuser IS '최고 슈퍼유저 권한 여부 (0:일반, 1:전체권한)';
COMMENT ON COLUMN JIPDAUM_BANNER.is_active IS '배너 활성화 여부 (0:비활성, 1:활성)';
COMMENT ON COLUMN JIPDAUM_NOTICE.is_active IS '공지사항 노출 여부 (0:미노출, 1:노출)';
COMMENT ON COLUMN JIPDAUM_ORDER_ITEM.ordered_price IS '주문 시점의 가구 변동 가격 스냅샷';
COMMENT ON COLUMN JIPDAUM_PAYMENT.method IS '결제 수단 (KAKAO, TOSS, CARD, BANK)';
COMMENT ON COLUMN JIPDAUM_PAYMENT.status IS '결제 상태 (PENDING, SUCCESS, FAILED, REFUNDED)';
COMMENT ON COLUMN JIPDAUM_POST_TAGGED_PRODUCT.tag_position_x IS '사진 내 가로 위치 비율 (%)';
COMMENT ON COLUMN JIPDAUM_POST_TAGGED_PRODUCT.tag_position_y IS '사진 내 세로 위치 비율 (%)';

COMMIT;