# Generated by Django 6.0.5 on 2026-06-05 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('KAKAO', '카카오페이'), ('TOSS', '토스'), ('CARD', '신용카드'), ('BANK', '계좌이체')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', '결제대기'), ('SUCCESS', '결제완료'), ('FAILED', '결제실패'), ('REFUNDED', '환불완료')], default='PENDING', max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제 내역',
                'verbose_name_plural': '결제 내역 목록',
                'db_table': 'JIPDAUM_PAYMENT',
            },
        ),
    ]
