# Generated by Django 6.0.5 on 2026-06-22 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('KAKAO', '카카오페이'), ('NAVER', '네이버페이'), ('TOSS', '토스'), ('CARD', '신용카드'), ('BANK', '계좌이체')], max_length=50),
        ),
    ]
