# Generated by Django 6.0.5 on 2026-09-06 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '1:1 문의',
                'verbose_name_plural': '1:1 문의 목록',
                'db_table': 'JIPDAUM_INQUIRY',
                'ordering': ['-created_at'],
            },
        ),
    ]
