# Generated by Django 6.0.5 on 2026-06-23 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='쿠폰 코드')),
                ('name', models.CharField(max_length=100, verbose_name='쿠폰명')),
                ('discount_type', models.CharField(choices=[('FIXED', '정액 할인'), ('PERCENT', '정률 할인')], max_length=10, verbose_name='할인 방식')),
                ('discount_value', models.PositiveIntegerField(verbose_name='할인값 (원 또는 %)')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='최소 주문 금액')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 할인 금액 (정률용)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='총 사용 제한 (null=무제한)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_personal', models.BooleanField(default=False, verbose_name='개인 발급 전용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰 목록',
                'db_table': 'JIPDAUM_COUPON',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 쿠폰',
                'verbose_name_plural': '유저 쿠폰 목록',
                'db_table': 'JIPDAUM_USER_COUPON',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
